---
kind: pipeline
type: docker
name: main-pipeline

steps:
  - name: cargo-fmt
    image: casperlabs/casper-node-launcher-build
    commands:
      - rustup update stable
      - cargo fmt -- --check

  - name: cargo-clippy
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo clippy -- --deny warnings

  - name: cargo-audit
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo audit --deny warnings

  - name: test
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo test

  - name: build-deb
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo deb

  - name: build-rpm
    image: casperlabs/rpm-package
    commands:
      - cargo rpm build -v

trigger:
  branch:
    - main
    - trying
    - staging
    - "release-*"
  event:
    exclude:
      - tag

---
kind: pipeline
type: docker
name: failed-main

clone:
  disable: true

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template:
        - |
          casper-node-launcher build status: *{{ uppercasefirst build.status }}*
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
    - failure
  branch:
    - main
    - trying
    - staging
    - "release-*"
  event:
    exclude:
      - tag

depends_on:
  - main-pipeline
---
kind: pipeline
type: docker
name: release-by-tag

steps:
  - name: build-deb
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo deb

  - name: publish-repo-prod
    image: casperlabs/aptly:latest
    failure: ignore
    environment:
      AWS_SECRET_ACCESS_KEY:
        from_secret: aptly_prod_secret_key
      AWS_ACCESS_KEY_ID:
        from_secret: aptly_prod_key_id
    settings:
      repo_name:
        from_secret: aptly_prod_repo
      region:
        from_secret: aptly_prod_region
      gpg_key:
        from_secret: aptly_prod_gpg_key
      gpg_pass:
        from_secret: aptly_prod_gpg_pass
      distribution_id:
        from_secret: aptly_prod_dist_id
      acl: 'public-read'
      prefix: 'releases'
      deb_path: './target/debian'
      deb_name: '*.deb'

  - name: build-rpm
    image: casperlabs/rpm-package
    commands:
      - cargo rpm build -v


  - name: publish-github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
        - md5
      files:
        - "./target/debian/*.deb"
        - "./target/release/rpmbuild/RPMS/x86_64/*.rpm"
      prerelease:
        - true
    when:
      ref:
        - refs/tags/v*

trigger:
  ref:
    - refs/tags/v*
---
kind: pipeline
type: docker
name: failed-publish

clone:
  disable: true

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template:
        - |
          casper-node-launcher build status: *{{ uppercasefirst build.status }}*
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
    - failure
  ref:
    - refs/tags/v*

depends_on:
  - release-by-tag
